import "./globals.css";
import ThemeInitializer from "@/components/ThemeInitializer";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <head>
        <ThemeInitializer />
      </head>
      <body className="min-h-full flex flex-col bg-slate-50 text-zinc-950 dark:bg-[#030014] dark:text-white" suppressHydrationWarning>
        <Navbar/>
        {children}
        <ToastContainer />
        <Footer/>
        </body>
    </html>
  );
}
